# Use an official Python runtime as a parent image
FROM python:3.8-slim

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Run the web server with Gunicorn on port 8080
CMD exec gunicorn --bind :8080 --workers 1 --threads 8 --timeout 0 app:app
